version: '3'
services:
  nats:
    image: nats
    restart: always
    ports:
      - 4222:4222
      - 8888:8222
    volumes:
      - ./streamdata:/data
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
